//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad3PLogBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cad3PLogBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apiview {
            get {
                object obj = ResourceManager.GetObject("apiview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apiview2 {
            get {
                object obj = ResourceManager.GetObject("apiview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Branch to CSV.
        /// </summary>
        internal static string DIALOG_EXPORT_BRANCH_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_EXPORT_BRANCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line number..
        /// </summary>
        internal static string ERR_INVALID_LINE_NUMBER {
            get {
                return ResourceManager.GetString("ERR_INVALID_LINE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookmarks set.\n\nPress Ctrl+B to bookmark the current line..
        /// </summary>
        internal static string ERR_NO_BOOKMARKS {
            get {
                return ResourceManager.GetString("ERR_NO_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No call tree data to export.\nLoad a log file first..
        /// </summary>
        internal static string ERR_NO_CALL_TREE_DATA {
            get {
                return ResourceManager.GetString("ERR_NO_CALL_TREE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log data to export..
        /// </summary>
        internal static string ERR_NO_DATA_TO_EXPORT {
            get {
                return ResourceManager.GetString("ERR_NO_DATA_TO_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERR_NO_FILE_LOADED.
        /// </summary>
        internal static string ERR_NO_FILE_LOADED {
            get {
                return ResourceManager.GetString("ERR_NO_FILE_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flame graph data to export.\nLoad a log file and view the Flame Graph tab first..
        /// </summary>
        internal static string ERR_NO_FLAME_GRAPH_DATA {
            get {
                return ResourceManager.GetString("ERR_NO_FLAME_GRAPH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No performance data to export.\nLoad a log file first..
        /// </summary>
        internal static string ERR_NO_PERFORMANCE_DATA {
            get {
                return ResourceManager.GetString("ERR_NO_PERFORMANCE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timeline data to export.\nLoad a log file and view the Timeline tab first..
        /// </summary>
        internal static string ERR_NO_TIMELINE_DATA {
            get {
                return ResourceManager.GetString("ERR_NO_TIMELINE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation was cancelled..
        /// </summary>
        internal static string ERR_SAVE_CANCELLED {
            get {
                return ResourceManager.GetString("ERR_SAVE_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string FILTER_CSV_FILES {
            get {
                return ResourceManager.GetString("FILTER_CSV_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_ball {
            get {
                object obj = ResourceManager.GetObject("green_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch exported to:\n{0}.
        /// </summary>
        internal static string MSG_BRANCH_EXPORTED {
            get {
                return ResourceManager.GetString("MSG_BRANCH_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open browser:\n{0}.
        /// </summary>
        internal static string MSG_BROWSER_LAUNCH_ERROR {
            get {
                return ResourceManager.GetString("MSG_BROWSER_LAUNCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call tree exported to:\n{0}.
        /// </summary>
        internal static string MSG_CALL_TREE_EXPORTED_JSON {
            get {
                return ResourceManager.GetString("MSG_CALL_TREE_EXPORTED_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call tree exported to:\n{0}.
        /// </summary>
        internal static string MSG_CALL_TREE_EXPORTED_XML {
            get {
                return ResourceManager.GetString("MSG_CALL_TREE_EXPORTED_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} line(s) saved..
        /// </summary>
        internal static string MSG_FILE_SAVED {
            get {
                return ResourceManager.GetString("MSG_FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Flame graph exported to:\n{0}.
        /// </summary>
        internal static string MSG_FLAME_GRAPH_EXPORTED {
            get {
                return ResourceManager.GetString("MSG_FLAME_GRAPH_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure the Grok URL in Options &gt; Settings first.\n\nExample: https://grok.example.com/search?q=.
        /// </summary>
        internal static string MSG_GROK_NOT_CONFIGURED {
            get {
                return ResourceManager.GetString("MSG_GROK_NOT_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file: {0}\n\n{1}\n\n{2}.
        /// </summary>
        internal static string MSG_LOAD_ERROR {
            get {
                return ResourceManager.GetString("MSG_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors found in this log file..
        /// </summary>
        internal static string MSG_NO_ERRORS {
            get {
                return ResourceManager.GetString("MSG_NO_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching pair found..
        /// </summary>
        internal static string MSG_NO_MATCHING_PAIR {
            get {
                return ResourceManager.GetString("MSG_NO_MATCHING_PAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No warnings found in this log file..
        /// </summary>
        internal static string MSG_NO_WARNINGS {
            get {
                return ResourceManager.GetString("MSG_NO_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected line is not an API call line..
        /// </summary>
        internal static string MSG_NOT_API_CALL {
            get {
                return ResourceManager.GetString("MSG_NOT_API_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found..
        /// </summary>
        internal static string MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results exported to:\n{0}.
        /// </summary>
        internal static string MSG_RESULTS_EXPORTED {
            get {
                return ResourceManager.GetString("MSG_RESULTS_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save file:\n{0}.
        /// </summary>
        internal static string MSG_SAVE_ERROR {
            get {
                return ResourceManager.GetString("MSG_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline exported to:\n{0}.
        /// </summary>
        internal static string MSG_TIMELINE_EXPORTED {
            get {
                return ResourceManager.GetString("MSG_TIMELINE_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_ball {
            get {
                object obj = ResourceManager.GetObject("red_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWGM CAD 3P Log Browser.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap treeview {
            get {
                object obj = ResourceManager.GetObject("treeview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not export performance data:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_PERFORMANCE_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_PERFORMANCE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line number must be between 1 and {0}..
        /// </summary>
        internal static string ERR_LINE_NUMBER_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERR_LINE_NUMBER_OUT_OF_RANGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find ENTER/EXIT pair for '{0}'..
        /// </summary>
        internal static string ERR_NO_ENTER_EXIT_PAIR {
            get {
                return ResourceManager.GetString("ERR_NO_ENTER_EXIT_PAIR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save branch:\n{0}.
        /// </summary>
        internal static string ERR_SAVE_BRANCH_FAILED {
            get {
                return ResourceManager.GetString("ERR_SAVE_BRANCH_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches found for '{0}'..
        /// </summary>
        internal static string ERR_NO_MATCHES_FOUND {
            get {
                return ResourceManager.GetString("ERR_NO_MATCHES_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not export Call Graph:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_CALL_GRAPH_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_CALL_GRAPH_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to copy to clipboard:\n{0}.
        /// </summary>
        internal static string ERR_COPY_FAILED {
            get {
                return ResourceManager.GetString("ERR_COPY_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export tree:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_TREE_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_TREE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export timeline:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_TIMELINE_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_TIMELINE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export flame graph:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_FLAME_GRAPH_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_FLAME_GRAPH_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to change font:\n{0}.
        /// </summary>
        internal static string ERR_FONT_CHANGE_FAILED {
            get {
                return ResourceManager.GetString("ERR_FONT_CHANGE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Branch exported to:\n{0}.
        /// </summary>
        internal static string MSG_BRANCH_EXPORTED_TO {
            get {
                return ResourceManager.GetString("MSG_BRANCH_EXPORTED_TO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Performance data exported to:\n{0}.
        /// </summary>
        internal static string MSG_PERFORMANCE_EXPORTED_TO {
            get {
                return ResourceManager.GetString("MSG_PERFORMANCE_EXPORTED_TO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} line(s) saved to:\n{1}.
        /// </summary>
        internal static string MSG_BRANCH_SAVED_TO {
            get {
                return ResourceManager.GetString("MSG_BRANCH_SAVED_TO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call Graph exported to:\n{0}.
        /// </summary>
        internal static string MSG_CALL_GRAPH_EXPORTED_TO {
            get {
                return ResourceManager.GetString("MSG_CALL_GRAPH_EXPORTED_TO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string DIALOG_TITLE_BOOKMARKS {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_BOOKMARKS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export file:\n{0}.
        /// </summary>
        internal static string ERR_EXPORT_FILE_FAILED {
            get {
                return ResourceManager.GetString("ERR_EXPORT_FILE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' not found..
        /// </summary>
        internal static string ERR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression:\n{0}.
        /// </summary>
        internal static string ERR_INVALID_REGEX {
            get {
                return ResourceManager.GetString("ERR_INVALID_REGEX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open updates page:\n{0}.
        /// </summary>
        internal static string ERR_OPEN_UPDATES_FAILED {
            get {
                return ResourceManager.GetString("ERR_OPEN_UPDATES_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open issues page:\n{0}.
        /// </summary>
        internal static string ERR_OPEN_ISSUES_FAILED {
            get {
                return ResourceManager.GetString("ERR_OPEN_ISSUES_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open help file:\n{0}.
        /// </summary>
        internal static string ERR_OPEN_HELP_FAILED {
            get {
                return ResourceManager.GetString("ERR_OPEN_HELP_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to open browser:\n{0}.
        /// </summary>
        internal static string ERR_BROWSER_FAILED {
            get {
                return ResourceManager.GetString("ERR_BROWSER_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help file (Cad3PLogBrowser.chm) not found....
        /// </summary>
        internal static string MSG_HELP_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_HELP_FILE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
